# Generated by Django 5.2 on 2026-01-21 18:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='School name', max_length=255)),
                ('slug', models.SlugField(help_text="URL path identifier (e.g., 'greenwood-academy')", max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must contain only lowercase letters, numbers, and hyphens', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='School address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the school is active')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the school has been verified')),
                ('trial_start_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('school_name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'School Invitation',
                'verbose_name_plural': 'School Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('free', 'Free Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('custom', 'Custom')], max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the plan', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Plan description')),
                ('monthly_price', models.IntegerField(default=0, help_text='Monthly price in kobo', validators=[django.core.validators.MinValueValidator(0)])),
                ('annual_price', models.IntegerField(default=0, help_text='Annual price in kobo (usually discounted)', validators=[django.core.validators.MinValueValidator(0)])),
                ('paystack_monthly_plan_code', models.CharField(blank=True, max_length=100)),
                ('paystack_annual_plan_code', models.CharField(blank=True, max_length=100)),
                ('max_admin_accounts', models.IntegerField(default=1, help_text='Maximum admin accounts allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_daily_emails', models.IntegerField(default=300, help_text='Maximum emails per day (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)])),
                ('has_import_feature', models.BooleanField(default=False, help_text='Whether CSV import is available')),
                ('trial_days', models.IntegerField(default=30, help_text='Number of trial days for new schools', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this plan is visible on pricing page')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('paystack_customer_code', models.CharField(blank=True, max_length=100)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=100)),
                ('paystack_email_token', models.CharField(blank=True, help_text='Token for managing subscription via email', max_length=100)),
                ('paystack_authorization_code', models.CharField(blank=True, help_text='Saved card authorization for recurring charges', max_length=100)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('emails_sent_today', models.IntegerField(default=0)),
                ('email_counter_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.school')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.IntegerField(help_text='Amount in kobo')),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='e.g., card, bank_transfer', max_length=50)),
                ('card_type', models.CharField(blank=True, help_text='e.g., visa, mastercard', max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('plan_name', models.CharField(max_length=100)),
                ('billing_cycle', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.subscription')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
