# Generated by Django 5.2 on 2026-01-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='accent_color',
            field=models.CharField(default='#2563eb', help_text='Primary accent color in hex format (e.g., #2563eb)', max_length=7),
        ),
        migrations.AddField(
            model_name='school',
            name='email_sender_name',
            field=models.CharField(blank=True, help_text="Name to display as email sender (e.g., 'Greenwood Academy')", max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(default='#4f46e5', help_text='Secondary color in hex format', max_length=7),
        ),
        migrations.AddField(
            model_name='school',
            name='tagline',
            field=models.CharField(blank=True, help_text='School tagline/motto', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, help_text='School website URL'),
        ),
    ]
