# Generated by Django 5.2 on 2026-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_portal_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='current_academic_year',
            field=models.CharField(default='2024/2025', help_text='Current academic year (e.g., 2024/2025)', max_length=9),
        ),
        migrations.AddField(
            model_name='school',
            name='current_term',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], default='First Term', help_text='Current term', max_length=20),
        ),
    ]
