# Generated by Django 5.2 on 2026-01-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_school_current_academic_year_school_current_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='current_academic_year',
            field=models.CharField(blank=True, help_text='Current academic year (e.g., 2024/2025) - Set when first session is created', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='current_term',
            field=models.CharField(blank=True, choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], help_text='Current term - Set when first session is created', max_length=20, null=True),
        ),
    ]
