# Generated by Django 5.2 on 2026-02-02 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_school_current_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_import_rows',
            field=models.IntegerField(default=0, help_text='Maximum students per XLSX import (0 = not available)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
