# Generated by Django 5.2 on 2026-02-02 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_max_import_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_parents',
            field=models.IntegerField(default=50, help_text='Maximum parent accounts (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_principals',
            field=models.IntegerField(default=1, help_text='Maximum principal accounts (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_students',
            field=models.IntegerField(default=50, help_text='Maximum student accounts (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_teachers',
            field=models.IntegerField(default=5, help_text='Maximum teacher accounts (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
