# Generated by Django 5.2 on 2026-02-02 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_add_user_limit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_proprietors',
            field=models.IntegerField(default=0, help_text='Maximum proprietor accounts (0 = not available)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
