# Generated by Django 5.2 on 2026-02-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_subscriptionplan_max_proprietors'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_staff_management',
            field=models.BooleanField(default=False, help_text='Whether staff management (Book On/Off) is available'),
        ),
    ]
