# Generated by Django 5.2 on 2026-02-17 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_subscriptionplan_has_staff_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_expiry_warning_sent',
            field=models.CharField(blank=True, default='', help_text='Last expiry warning milestone sent (pre_7, pre_3, pre_1, grace_1, grace_3, grace_5)', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='grace_period_days',
            field=models.IntegerField(default=5, help_text='Number of grace days after expiry before full lockout (0 = no grace)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace_period', 'Grace Period'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20),
        ),
    ]
