# Generated by Django 5.2 on 2026-02-18 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_add_pending_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_expiry_warning_sent',
            field=models.CharField(blank=True, default='', help_text='Last expiry warning milestone sent (pre_7, pre_3, pre_1, grace_1, grace_2, grace_3, grace_4, grace_5)', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_parents',
            field=models.IntegerField(default=300, help_text='Maximum parent accounts (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_students',
            field=models.IntegerField(default=300, help_text='Maximum student accounts (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_teachers',
            field=models.IntegerField(default=20, help_text='Maximum teacher accounts (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('custom', 'Custom')], max_length=50, unique=True),
        ),
    ]
