# Generated by Django 5.2 on 2026-02-20 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_add_onboarding_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrecord',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=30, help_text='Number of trial days for new schools (standard free trial)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
