# Generated by Django 5.2 on 2026-02-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_create_support_ticket_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='lesson_note_weeks_per_term',
            field=models.PositiveSmallIntegerField(default=12, help_text='Number of weeks per term — sets how many lesson notes each teacher must submit per subject'),
        ),
    ]
