# Generated by Django 5.2 on 2025-04-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='academic_year',
            field=models.CharField(default='2024/2025', max_length=9),
        ),
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='term',
            field=models.CharField(default='First Term', max_length=20),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'academic_year', 'term')},
        ),
    ]
