# Generated by Django 5.2 on 2025-09-04 14:41

import academics.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_studentsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('assignment', 'Assignment'), ('note', 'Class Note'), ('announcement', 'Announcement')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to=academics.models.upload_to_subject_files)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Required for assignments', null=True)),
                ('max_score', models.PositiveIntegerField(blank=True, help_text='Maximum score for assignment', null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentContentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_views', to='academics.subjectcontent')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subjectcontent',
            index=models.Index(fields=['subject', 'content_type'], name='academics_s_subject_52c40f_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectcontent',
            index=models.Index(fields=['created_at'], name='academics_s_created_81d872_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcontentview',
            unique_together={('student', 'content')},
        ),
    ]
