# Generated by Django 5.2 on 2025-09-04 16:12

import academics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subjectcontent_studentcontentview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcontent',
            name='file',
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='File attachment', upload_to=academics.models.upload_to_content_files)),
                ('original_name', models.CharField(help_text='Original filename when uploaded', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type_mime', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='academics.subjectcontent')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
