# Generated by Django 5.2 on 2025-09-30 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_subjectcontent_file_contentfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcontent',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subjectcontent',
            name='created_by',
            field=models.ForeignKey(help_text='Teacher who originally created this content', limit_choices_to={'role__in': ['teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
