# Generated by Django 5.2 on 2025-10-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_assignmentsubmission_submissionfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of times student has submitted (max 2)'),
        ),
    ]
