# Generated by Django 5.2 on 2025-10-26 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_assignmentsubmission_submission_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('test', 'Test'), ('exam', 'Exam')], max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the assessment in minutes')),
                ('assessment_date', models.DateField(help_text='Date when the assessment will be conducted')),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Total marks for this assessment', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.subject')),
            ],
            options={
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('marks', models.DecimalField(decimal_places=2, help_text='Marks allocated to this question', max_digits=5)),
                ('question_number', models.PositiveIntegerField(help_text='Question number/order')),
                ('is_active', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.assessment')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['subject', 'assessment_type'], name='academics_a_subject_db7ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_date'], name='academics_a_assessm_64380a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('assessment', 'question_number')},
        ),
    ]
