# Generated by Django 5.2 on 2025-10-27 07:41

import academics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_assessment_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for exam questions (max 100KB)', null=True, upload_to=academics.models.upload_to_exam_images),
        ),
    ]
