# Generated by Django 5.2 on 2025-10-27 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Correct answer for fill-in-the-blanks or essay marking guide'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blanks'), ('essay', 'Essay/Short Answer'), ('matching', 'Matching')], default='multiple_choice', help_text='Type of question', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('test_1', 'Test 1'), ('test_2', 'Test 2'), ('mid_term', 'Mid-Term Test'), ('final_exam', 'Final Exam')], max_length=10),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Topic or chapter name (e.g., 'Algebra', 'Grammar', 'Photosynthesis')", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of topic in curriculum')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.subject')),
            ],
            options={
                'ordering': ['subject', 'order', 'name'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Topic/Chapter this assessment covers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='academics.topic'),
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_item', models.CharField(help_text='Item on the left side', max_length=500)),
                ('right_item', models.CharField(help_text='Item on the right side (correct match)', max_length=500)),
                ('pair_number', models.PositiveIntegerField(help_text='Pair number/order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='academics.question')),
            ],
            options={
                'ordering': ['pair_number'],
                'unique_together': {('question', 'pair_number')},
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(help_text="Option text (e.g., 'The capital of France')")),
                ('option_label', models.CharField(help_text='Option label (A, B, C, D, etc.)', max_length=5)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this is the correct answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='academics.question')),
            ],
            options={
                'ordering': ['order', 'option_label'],
                'unique_together': {('question', 'option_label')},
            },
        ),
    ]
