# Generated by Django 5.2 on 2025-10-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_question_correct_answer_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_date',
            field=models.DateField(blank=True, help_text='Date when the assessment will be conducted (set by admin)', null=True),
        ),
    ]
