# Generated by Django 5.2 on 2025-10-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_assessment_assessment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_released',
            field=models.BooleanField(default=False, help_text='Whether students can see this assessment (controlled by admin)'),
        ),
    ]
