# Generated by Django 5.2 on 2025-10-28 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_assessment_is_released'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.PositiveIntegerField(help_text='Time taken in seconds')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score obtained (auto-calculated for objective questions)', max_digits=6, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum possible score', max_digits=6)),
                ('is_graded', models.BooleanField(default=False, help_text='Whether essay/fill-blank questions have been manually graded')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='Text answer for non-multiple choice questions')),
                ('matching_answers', models.JSONField(blank=True, help_text='Matching question answers as JSON', null=True)),
                ('is_correct', models.BooleanField(blank=True, help_text='Whether the answer is correct (null for essay/manual grading)', null=True)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, help_text='Points earned for this question', max_digits=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='academics.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_selections', to='academics.questionoption')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academics.assessmentsubmission')),
            ],
            options={
                'ordering': ['question__question_number'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentsubmission',
            index=models.Index(fields=['student', 'assessment'], name='academics_a_student_545c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubmission',
            index=models.Index(fields=['submitted_at'], name='academics_a_submitt_f8261b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsubmission',
            unique_together={('assessment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('submission', 'question')},
        ),
    ]
