# Generated by Django 5.2 on 2025-11-15 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_assessmentsubmission_studentanswer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='report_sent',
            field=models.BooleanField(default=False, help_text='Whether report sheet has been sent to student and parent'),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='report_sent_by',
            field=models.ForeignKey(blank=True, help_text='Admin who sent the report', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='report_sent_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when report was sent', null=True),
        ),
    ]
