# Generated by Django 5.2 on 2025-11-25 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_studentsession_report_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('General', 'General'), ('Science', 'Science'), ('Arts', 'Arts'), ('Commercial', 'Commercial')], help_text='Department name', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this class belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='academics.department'),
        ),
    ]
