# Generated by Django 5.2 on 2025-11-25 03:21

from django.db import migrations


def populate_departments(apps, schema_editor):
    """Create the 3 standard departments (Science, Arts, Commercial)"""
    Department = apps.get_model('academics', 'Department')

    departments = [
        {'name': 'Science', 'description': 'Science department for senior classes'},
        {'name': 'Arts', 'description': 'Arts department for senior classes'},
        {'name': 'Commercial', 'description': 'Commercial department for senior classes'},
    ]

    for dept_data in departments:
        Department.objects.get_or_create(
            name=dept_data['name'],
            defaults={'description': dept_data['description']}
        )


def reverse_populate_departments(apps, schema_editor):
    """Remove the departments"""
    Department = apps.get_model('academics', 'Department')
    Department.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_department_class_department'),
    ]

    operations = [
        migrations.RunPython(populate_departments, reverse_populate_departments),
    ]
