# Generated by Django 5.2 on 2025-11-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_populate_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='department',
        ),
        migrations.AddField(
            model_name='class',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments available in this class (e.g., S.S.S.1 can have Science, Arts, Commercial)', related_name='classes', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Commercial', 'Commercial')], help_text='Department name', max_length=20, unique=True),
        ),
    ]
