# Generated by Django 5.2 on 2025-11-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_remove_class_department_class_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='departments',
        ),
        migrations.AddField(
            model_name='class',
            name='has_departments',
            field=models.BooleanField(default=False, help_text='If True, students and subjects in this class must select a department (Science/Arts/Commercial)'),
        ),
    ]
