# Generated by Django 5.2 on 2025-12-09 20:22

import academics.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_remove_class_departments_class_has_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(storage=academics.storage.AssignmentFileStorage(), upload_to='submissions/%Y/%m/%d/'),
        ),
    ]
