# Generated by Django 5.2 on 2025-12-09 20:29

import academics.models
import academics.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_alter_submissionfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='file',
            field=models.FileField(help_text='File attachment', storage=academics.storage.AssignmentFileStorage(), upload_to=academics.models.upload_to_content_files),
        ),
    ]
