# Generated by Django 5.2 on 2025-12-11 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_alter_contentfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False, help_text='Whether this student has access to this assessment')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, help_text='When access was granted')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='academics.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_access', to=settings.AUTH_USER_MODEL)),
                ('unlocked_by', models.ForeignKey(blank=True, help_text='Admin/Principal who granted access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_unlocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'indexes': [models.Index(fields=['student', 'assessment'], name='academics_a_student_060ad3_idx'), models.Index(fields=['is_unlocked'], name='academics_a_is_unlo_d07615_idx')],
                'unique_together': {('assessment', 'student')},
            },
        ),
    ]
