# Generated by Django 5.2 on 2026-01-27 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_class_school_alter_class_name_and_more'),
        ('tenants', '0003_add_portal_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.school'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Commercial', 'Commercial')], help_text='Department name', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'name')},
        ),
    ]
