# Generated by Django 5.2 on 2026-01-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_department_school_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='academic_year',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='term',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], max_length=20),
        ),
    ]
