# Generated by Django 5.2 on 2026-02-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_alter_classsession_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_final_class',
            field=models.BooleanField(default=False, help_text='If True, students completing this class will graduate.'),
        ),
        migrations.AddField(
            model_name='class',
            name='next_class',
            field=models.ForeignKey(blank=True, help_text='The class students advance to after this one. Leave empty for the final class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_classes', to='academics.class'),
        ),
    ]
