# Generated by Django 5.2 on 2026-02-17 14:03

from django.db import migrations


PROGRESSION = [
    ('J.S.S.1', 'J.S.S.2', False),
    ('J.S.S.2', 'J.S.S.3', False),
    ('J.S.S.3', 'S.S.S.1', False),
    ('S.S.S.1', 'S.S.S.2', False),
    ('S.S.S.2', 'S.S.S.3', False),
    ('S.S.S.3', None, True),
]


def populate_progression(apps, schema_editor):
    Class = apps.get_model('academics', 'Class')
    school_ids = Class.objects.values_list('school_id', flat=True).distinct()

    for school_id in school_ids:
        classes = {c.name: c for c in Class.objects.filter(school_id=school_id)}
        for current_name, next_name, is_final in PROGRESSION:
            if current_name in classes:
                cls = classes[current_name]
                cls.is_final_class = is_final
                if next_name and next_name in classes:
                    cls.next_class = classes[next_name]
                cls.save()


def reverse_progression(apps, schema_editor):
    Class = apps.get_model('academics', 'Class')
    Class.objects.all().update(next_class=None, is_final_class=False)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_class_is_final_class_class_next_class'),
    ]

    operations = [
        migrations.RunPython(populate_progression, reverse_progression),
    ]
