# Generated by Django 5.2 on 2025-04-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
