# Generated by Django 5.2 on 2025-10-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0002_alter_attendancerecord_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesummary',
            name='attendance_finalized',
            field=models.BooleanField(default=False, help_text="If True, attendance score won't be auto-updated from attendance records"),
        ),
    ]
