# Generated by Django 5.2 on 2025-10-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0003_gradesummary_attendance_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesummary',
            name='exam_manual_entry',
            field=models.BooleanField(default=False, help_text='If True, exam score was manually entered by teacher and cannot be edited again'),
        ),
        migrations.AddField(
            model_name='gradesummary',
            name='test_manual_entry',
            field=models.BooleanField(default=False, help_text='If True, test score was manually entered by teacher and cannot be edited again'),
        ),
    ]
