# Generated by Django 5.2 on 2025-11-18 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0004_gradesummary_exam_manual_entry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('term', models.CharField(choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term'), ('3rd Term', '3rd Term')], max_length=20)),
                ('total_fees', models.DecimalField(decimal_places=2, help_text='Total fees for the term', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Outstanding balance', max_digits=10)),
                ('payment_method', models.CharField(blank=True, help_text='Cash, Transfer, etc.', max_length=50)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='fee_receipts/')),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_issued', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='fee_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_issued'],
                'indexes': [models.Index(fields=['student', 'academic_year', 'term'], name='schooladmin_student_16a5aa_idx'), models.Index(fields=['receipt_number'], name='schooladmin_receipt_c6ef28_idx')],
            },
        ),
    ]
