# Generated by Django 5.2 on 2025-11-18 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0005_feereceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('adjustment', 'Adjustment'), ('refund', 'Refund')], default='payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='schooladmin.studentfeerecord')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fee Payment Histories',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
