# Generated by Django 5.2 on 2025-11-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0007_alter_feereceipt_term_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date to send the announcement', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Time to send the announcement', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='send_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='send_type',
            field=models.CharField(choices=[('manual', 'Send Manually'), ('scheduled', 'Schedule for Later')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
