# Generated by Django 5.2 on 2025-11-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0008_announcement_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this announcement should be sent repeatedly'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='last_sent_date',
            field=models.DateField(blank=True, help_text='Last date this recurring announcement was sent', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='next_send_date',
            field=models.DateField(blank=True, help_text='Next scheduled send date for recurring announcements', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='parent_filter',
            field=models.CharField(choices=[('all', 'All Parents'), ('owing_fees', 'Parents with Students Owing Fees'), ('low_attendance', 'Parents with Students Having Attendance Below 50%')], default='all', help_text='Filter criteria for parent recipients', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='recurrence_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days between recurring sends (e.g., 10 means every 10 days)', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='student_filter',
            field=models.CharField(choices=[('all', 'All Students'), ('owing_fees', 'Students Owing Fees'), ('low_attendance', 'Students with Attendance Below 50%'), ('low_assignment', 'Students with Assignment Scores Below 50%'), ('low_test', 'Students with Test Scores Below 50%')], default='all', help_text='Filter criteria for student recipients', max_length=20),
        ),
    ]
