# Generated by Django 5.2 on 2025-11-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0009_announcement_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='grading_deadline',
            field=models.DateField(blank=True, help_text='Deadline date for grading completion (e.g., exam end date)', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='teacher_filter',
            field=models.CharField(choices=[('all', 'All Teachers'), ('incomplete_grading', 'Teachers with Incomplete Grading After Deadline')], default='all', help_text='Filter criteria for teacher recipients', max_length=30),
        ),
    ]
