# Generated by Django 5.2 on 2026-01-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0011_announcement_school_feestructure_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], max_length=20),
        ),
    ]
