# Generated by Django 5.2 on 2026-02-06 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0012_alter_feestructure_term'),
        ('tenants', '0009_subscriptionplan_has_staff_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'proprietor']}, on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StaffManagementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_late_booking', models.BooleanField(default=True, help_text='If False, block booking after grace period entirely')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_management_settings', to='tenants.school')),
            ],
        ),
        migrations.CreateModel(
            name='StaffScheduleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days', models.JSONField(help_text='List of weekday numbers: 0=Mon, 1=Tue, ..., 6=Sun')),
                ('start_time', models.TimeField(help_text='Scheduled start time')),
                ('end_time', models.TimeField(help_text='Scheduled end time')),
                ('grace_period_minutes', models.IntegerField(default=30, help_text='Minutes before/after scheduled time when booking is allowed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedule_groups', to='tenants.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='Date from which this assignment is active')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedule_assignments', to='tenants.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to=settings.AUTH_USER_MODEL)),
                ('schedule_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schooladmin.staffschedulegroup')),
            ],
            options={
                'ordering': ['-effective_from'],
                'unique_together': {('teacher', 'schedule_group')},
            },
        ),
        migrations.CreateModel(
            name='StaffAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduled_start', models.TimeField(help_text='Snapshot of scheduled start at time of booking')),
                ('scheduled_end', models.TimeField(help_text='Snapshot of scheduled end at time of booking')),
                ('book_on_time', models.DateTimeField(blank=True, help_text='Actual book-on timestamp', null=True)),
                ('book_off_time', models.DateTimeField(blank=True, help_text='Actual book-off timestamp', null=True)),
                ('book_on_status', models.CharField(blank=True, choices=[('ON_TIME', 'On Time'), ('LATE', 'Late')], max_length=10, null=True)),
                ('book_off_status', models.CharField(blank=True, choices=[('ON_TIME', 'On Time'), ('LATE', 'Late')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_records', to='tenants.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('schedule_group', models.ForeignKey(help_text='Snapshot of which schedule was active', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='schooladmin.staffschedulegroup')),
            ],
            options={
                'ordering': ['-date', 'teacher__last_name'],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
