# Generated by Django 5.2 on 2026-02-23 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_populate_class_progression'),
        ('schooladmin', '0014_deferred_graduation_email'),
        ('tenants', '0019_create_support_ticket_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingconfiguration',
            name='attendance_percentage',
            field=models.PositiveIntegerField(help_text='Percentage weight for attendance (0-20%). Set to 0 to disable attendance tracking.'),
        ),
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Typed lesson note content')),
                ('file', models.FileField(blank=True, help_text='Optional PDF or DOCX file attachment', null=True, upload_to='lesson_notes/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('admin_feedback', models.TextField(blank=True, help_text='Feedback from admin to teacher')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_rating', models.CharField(blank=True, choices=[('good', 'Good'), ('needs_improvement', 'Needs Improvement'), ('poor', 'Poor')], max_length=20)),
                ('ai_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_feedback_sent_to_teacher', models.BooleanField(default=False, help_text='True if the AI feedback was sent to the teacher as admin feedback')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When teacher submitted for review', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lesson_notes', to=settings.AUTH_USER_MODEL)),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_notes', to='academics.classsession')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lesson_notes', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to='tenants.school')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_lesson_notes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
