# Generated by Django 5.2 on 2026-02-24 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_populate_class_progression'),
        ('schooladmin', '0015_lesson_note'),
        ('tenants', '0020_add_lesson_note_weeks_per_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTopicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(help_text='Which week of the term this topic covers (1 to lesson_note_weeks_per_term)')),
                ('topic', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_topic_plans', to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_topic_plans', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_topic_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('teacher', 'subject', 'week_number')},
            },
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='topic_plan',
            field=models.OneToOneField(blank=True, help_text='The topic plan slot this note belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_note', to='schooladmin.lessontopicplan'),
        ),
    ]
