# Generated by Django 5.2 on 2025-09-09 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_subjectcontent_file_contentfile'),
        ('logs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment', 'New Assignments'), ('note', 'Class Notes'), ('announcement', 'Announcements'), ('grading', 'Grading Updates'), ('all', 'All Notifications')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('user_created', 'User Created'), ('content_created', 'Content Created'), ('content_updated', 'Content Updated'), ('content_deleted', 'Content Deleted'), ('assignment_graded', 'Assignment Graded'), ('login', 'User Login'), ('logout', 'User Logout'), ('system', 'System Activity')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='content_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the related content', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='content_title',
            field=models.CharField(blank=True, help_text='Title of the content', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='content_type',
            field=models.CharField(blank=True, choices=[('assignment', 'Assignment'), ('note', 'Class Note'), ('announcement', 'Announcement')], help_text='Type of content (assignment, note, announcement)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='is_notification',
            field=models.BooleanField(default=False, help_text='Whether this activity should appear as a notification'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject related to this activity', null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='logs_activi_user_id_0c4daf_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity_type', 'timestamp'], name='logs_activi_activit_282746_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['subject', 'timestamp'], name='logs_activi_subject_9c1249_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['is_notification', 'timestamp'], name='logs_activi_is_noti_352ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['subject', 'is_notification', 'timestamp'], name='logs_activi_subject_46f32b_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationstatus',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to='logs.activitylog'),
        ),
        migrations.AddField(
            model_name='notificationstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'notification_type'], name='logs_notifi_user_id_e401fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'notification_type')},
        ),
        migrations.AddIndex(
            model_name='notificationstatus',
            index=models.Index(fields=['user', 'is_read'], name='logs_notifi_user_id_818bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationstatus',
            index=models.Index(fields=['user', 'activity_log'], name='logs_notifi_user_id_38e271_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationstatus',
            index=models.Index(fields=['activity_log', 'is_read'], name='logs_notifi_activit_67f3b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationstatus',
            unique_together={('user', 'activity_log')},
        ),
    ]
