# Generated by Django 5.2 on 2025-11-16 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_notificationpreference_notificationstatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('report_release', 'Report Release'), ('incomplete_grades', 'Incomplete Grades'), ('fee_reminder', 'Fee Reminder'), ('general', 'General'), ('system', 'System')], default='general', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_popup_shown', models.BooleanField(default=False, help_text='Whether the popup has been shown to user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, help_text='Additional data for the notification', null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='logs_notifi_recipie_9dc104_idx'), models.Index(fields=['recipient', 'is_popup_shown'], name='logs_notifi_recipie_ed8442_idx'), models.Index(fields=['recipient', 'created_at'], name='logs_notifi_recipie_dfaee7_idx'), models.Index(fields=['notification_type', 'created_at'], name='logs_notifi_notific_309248_idx')],
            },
        ),
    ]
