# Generated by Django 5.2 on 2025-11-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_add_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_release', 'Report Release'), ('incomplete_grades', 'Incomplete Grades'), ('fee_reminder', 'Fee Reminder'), ('teacher_grading_reminder', 'Teacher Grading Reminder'), ('announcement', 'Announcement'), ('general', 'General'), ('system', 'System')], default='general', max_length=30),
        ),
    ]
