# Generated by Django 5.2 on 2025-09-11 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_remove_subjectcontent_file_contentfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_school_day', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('term', models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_sessions', models.ManyToManyField(help_text='Class sessions this calendar applies to', related_name='attendance_calendars', to='academics.classsession')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year', 'term'],
                'unique_together': {('academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='HolidayLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('school_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_label', to='attendance.schoolday')),
            ],
        ),
        migrations.CreateModel(
            name='SessionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('academic_year', 'term')},
            },
        ),
        migrations.AddField(
            model_name='schoolday',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_days', to='attendance.sessioncalendar'),
        ),
        migrations.CreateModel(
            name='AttendanceHolidayLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=100)),
                ('holiday_type', models.CharField(blank=True, choices=[('public', 'Public Holiday'), ('religious', 'Religious Holiday'), ('school', 'School Holiday'), ('break', 'Term Break'), ('other', 'Other')], default='public', max_length=50)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='attendance.attendancecalendar')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('calendar', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSchoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_type', models.CharField(blank=True, help_text="Type of school day (e.g., 'Regular', 'Exam Day', 'Half Day')", max_length=50)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_days', to='attendance.attendancecalendar')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('calendar', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.subject')),
                ('school_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.schoolday')),
            ],
            options={
                'unique_together': {('student', 'subject', 'school_day')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='schoolday',
            unique_together={('session', 'date')},
        ),
    ]
