# Generated by Django 5.2 on 2026-01-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancecalendar_school'),
        ('tenants', '0003_add_portal_user_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancecalendar',
            unique_together={('school', 'academic_year', 'term')},
        ),
    ]
