# Generated by Django 5.2 on 2025-04-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='term',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
