# Generated by Django 5.2 on 2025-04-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Commercial', 'Commercial')], max_length=20, null=True),
        ),
    ]
