# Generated by Django 5.2 on 2025-12-06 00:39

from django.db import migrations


def set_existing_users_verified(apps, schema_editor):
    """
    Set all existing users to verified so they can continue logging in.
    Only new users created after this migration will need email verification.
    """
    CustomUser = apps.get_model('users', 'CustomUser')

    # Update all existing users to verified status
    CustomUser.objects.all().update(
        email_verified=True,
        must_change_password=False
    )


def reverse_migration(apps, schema_editor):
    """
    Reverse operation - set users back to unverified if needed
    """
    # We don't want to reverse this, so just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RunPython(set_existing_users_verified, reverse_migration),
    ]
